### Training Configurations ###
dataset_dir: /home/ec2-user/data/datasets/10000_songs_03_31_18.npz
output_dir: /home/ec2-user/data/models/

total_pct: 1.0
train_pct: 0.8

train_bsz: 1
val_bsz: 16

queue_capacity: 100
queue_sleep: .01

optimizer: momentum
l2_weight_regularizer: 0.0005
loss_regularizer: 1.0
base_lr: 0.0001
decay_step_multiplier: .66
decay_rate: 0.95
momentum: 0.9
drop_rate: 0.0

eval_frequency: -1
save_frequency: -1
log_frequency: 1

num_epochs: 25

num_datapoints: 10000
num_feat: 16

metric_sample_size: 8000

tensorboard_port: 6009

debug: 0

network_config:
  batch_size: 1
  num_feat: 16

  architecture:
    primary_stream:
      fc1:
         type: fc
         out_size: 10
#       fc2:
#         type: fc
#         out_size: 10
      fc3:
        type: fc
        final_layer: True
        out_size: 1

